---
- name: Validate admin console password
  ansible.builtin.assert:
    that:
      - keycloak_quarkus_admin_pass | length > 12
    quiet: True
    fail_msg: "The console administrator password is empty or invalid. Please set the keycloak_quarkus_admin_pass variable to a 12+ char long string"
    success_msg: "{{ 'Console administrator password OK' }}"

- name: Validate configuration
  ansible.builtin.assert:
    that:
      - (keycloak_quarkus_ha_enabled and keycloak_quarkus_db_enabled) or (not keycloak_quarkus_ha_enabled and keycloak_quarkus_db_enabled) or (not keycloak_quarkus_ha_enabled and not keycloak_quarkus_db_enabled)
    quiet: True
    fail_msg: "Cannot install HA setup without a backend database service. Check keycloak_quarkus_ha_enabled and keycloak_quarkus_db_enabled"
    success_msg: "{{ 'Configuring HA' if keycloak_quarkus_ha_enabled else 'Configuring standalone' }}"

- name: Ensure required packages are installed
  ansible.builtin.include_tasks: fastpackages.yml
  vars:
    packages_list:
      - "{{ keycloak_quarkus_jvm_package }}"
      - unzip
      - procps-ng
      - initscripts
      - tzdata-java
